# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_prof_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newProfForm(object):
    def setupUi(self, newProfForm):
        newProfForm.setObjectName("newProfForm")
        newProfForm.resize(625, 438)
        self.profNameFrame = QtWidgets.QFrame(newProfForm)
        self.profNameFrame.setGeometry(QtCore.QRect(60, 60, 235, 45))
        self.profNameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profNameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profNameFrame.setObjectName("profNameFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.profNameFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.profNameLabel = QtWidgets.QLabel(self.profNameFrame)
        self.profNameLabel.setObjectName("profNameLabel")
        self.gridLayout.addWidget(self.profNameLabel, 0, 0, 1, 1)
        self.profName = QtWidgets.QLineEdit(self.profNameFrame)
        self.profName.setObjectName("profName")
        self.gridLayout.addWidget(self.profName, 0, 1, 1, 1)
        self.profIdFrame = QtWidgets.QFrame(newProfForm)
        self.profIdFrame.setGeometry(QtCore.QRect(340, 50, 235, 45))
        self.profIdFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profIdFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profIdFrame.setObjectName("profIdFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.profIdFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.profIdLabel = QtWidgets.QLabel(self.profIdFrame)
        self.profIdLabel.setObjectName("profIdLabel")
        self.gridLayout_2.addWidget(self.profIdLabel, 0, 0, 1, 1)
        self.profId = QtWidgets.QLineEdit(self.profIdFrame)
        self.profId.setObjectName("profId")
        self.gridLayout_2.addWidget(self.profId, 0, 1, 1, 1)
        self.profBaseFrame = QtWidgets.QFrame(newProfForm)
        self.profBaseFrame.setGeometry(QtCore.QRect(90, 150, 179, 45))
        self.profBaseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profBaseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profBaseFrame.setObjectName("profBaseFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.profBaseFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.profBaseLabel = QtWidgets.QLabel(self.profBaseFrame)
        self.profBaseLabel.setObjectName("profBaseLabel")
        self.gridLayout_3.addWidget(self.profBaseLabel, 0, 0, 1, 1)
        self.profBase = QtWidgets.QComboBox(self.profBaseFrame)
        self.profBase.setObjectName("profBase")
        self.gridLayout_3.addWidget(self.profBase, 0, 1, 1, 1)
        self.profGradeFrame = QtWidgets.QFrame(newProfForm)
        self.profGradeFrame.setGeometry(QtCore.QRect(380, 150, 179, 45))
        self.profGradeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profGradeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profGradeFrame.setObjectName("profGradeFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.profGradeFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.profGradeLabel = QtWidgets.QLabel(self.profGradeFrame)
        self.profGradeLabel.setObjectName("profGradeLabel")
        self.gridLayout_4.addWidget(self.profGradeLabel, 0, 0, 1, 1)
        self.profGrade = QtWidgets.QComboBox(self.profGradeFrame)
        self.profGrade.setObjectName("profGrade")
        self.gridLayout_4.addWidget(self.profGrade, 0, 1, 1, 1)
        self.confirmBtn = QtWidgets.QPushButton(newProfForm)
        self.confirmBtn.setGeometry(QtCore.QRect(330, 330, 121, 51))
        self.confirmBtn.setObjectName("confirmBtn")
        self.cancelBtn = QtWidgets.QPushButton(newProfForm)
        self.cancelBtn.setGeometry(QtCore.QRect(190, 330, 101, 51))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(newProfForm)
        QtCore.QMetaObject.connectSlotsByName(newProfForm)

    def retranslateUi(self, newProfForm):
        _translate = QtCore.QCoreApplication.translate
        newProfForm.setWindowTitle(_translate("newProfForm", "Form"))
        self.profNameLabel.setText(_translate("newProfForm", "Prof Name"))
        self.profIdLabel.setText(_translate("newProfForm", "Prof ID"))
        self.profBaseLabel.setText(_translate("newProfForm", "Prof Base"))
        self.profGradeLabel.setText(_translate("newProfForm", "Prof Grade"))
        self.confirmBtn.setText(_translate("newProfForm", "Confirm"))
        self.cancelBtn.setText(_translate("newProfForm", "Cancel"))
