# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_thesis_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newProfForm(object):
    def setupUi(self, newProfForm):
        newProfForm.setObjectName("newProfForm")
        newProfForm.resize(596, 188)
        self.gridLayout = QtWidgets.QGridLayout(newProfForm)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.profName = QtWidgets.QLineEdit(newProfForm)
        self.profName.setObjectName("profName")
        self.verticalLayout_8.addWidget(self.profName)
        self.lineEdit = QtWidgets.QLineEdit(newProfForm)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.profBase = QtWidgets.QComboBox(newProfForm)
        self.profBase.setObjectName("profBase")
        self.verticalLayout_8.addWidget(self.profBase)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.profNameLabel_2 = QtWidgets.QLabel(newProfForm)
        self.profNameLabel_2.setObjectName("profNameLabel_2")
        self.verticalLayout_7.addWidget(self.profNameLabel_2)
        self.profBaseLabel = QtWidgets.QLabel(newProfForm)
        self.profBaseLabel.setObjectName("profBaseLabel")
        self.verticalLayout_7.addWidget(self.profBaseLabel)
        self.label = QtWidgets.QLabel(newProfForm)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.profId = QtWidgets.QLineEdit(newProfForm)
        self.profId.setObjectName("profId")
        self.verticalLayout_6.addWidget(self.profId)
        self.profGrade = QtWidgets.QComboBox(newProfForm)
        self.profGrade.setObjectName("profGrade")
        self.verticalLayout_6.addWidget(self.profGrade)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.profIdLabel_2 = QtWidgets.QLabel(newProfForm)
        self.profIdLabel_2.setObjectName("profIdLabel_2")
        self.verticalLayout_5.addWidget(self.profIdLabel_2)
        self.profGradeLabel = QtWidgets.QLabel(newProfForm)
        self.profGradeLabel.setObjectName("profGradeLabel")
        self.verticalLayout_5.addWidget(self.profGradeLabel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancelBtn = QtWidgets.QPushButton(newProfForm)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_6.addWidget(self.cancelBtn)
        self.confirmBtn = QtWidgets.QPushButton(newProfForm)
        self.confirmBtn.setObjectName("confirmBtn")
        self.horizontalLayout_6.addWidget(self.confirmBtn)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)

        self.retranslateUi(newProfForm)
        QtCore.QMetaObject.connectSlotsByName(newProfForm)

    def retranslateUi(self, newProfForm):
        _translate = QtCore.QCoreApplication.translate
        newProfForm.setWindowTitle(_translate("newProfForm", "Form"))
        self.profNameLabel_2.setText(_translate("newProfForm", "<html><head/><body><p align=\"center\">شماره دانشجویی</p></body></html>"))
        self.profBaseLabel.setText(_translate("newProfForm", "<html><head/><body><p align=\"center\">آی‌دی استاد</p></body></html>"))
        self.label.setText(_translate("newProfForm", "<html><head/><body><p align=\"center\">مقطع پایان‌نامه</p></body></html>"))
        self.profIdLabel_2.setText(_translate("newProfForm", "<html><head/><body><p align=\"center\">نام و نام خانوادگی</p></body></html>"))
        self.profGradeLabel.setText(_translate("newProfForm", "<html><head/><body><p align=\"center\">وضعیت پایان‌نامه</p></body></html>"))
        self.cancelBtn.setText(_translate("newProfForm", "تایید"))
        self.confirmBtn.setText(_translate("newProfForm", "انصراف"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newProfForm = QtWidgets.QWidget()
    ui = Ui_newProfForm()
    ui.setupUi(newProfForm)
    newProfForm.show()
    sys.exit(app.exec_())
