# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from output_dialog import Ui_Dialog_Output as q


class Ui_inputFilesPrompt(object):
    def setupUi(self, inputFilesPrompt):
        self.inputFilesPrompt = inputFilesPrompt
        inputFilesPrompt.setObjectName("inputFilesPrompt")
        inputFilesPrompt.resize(692, 235)
        self.profSalaryFrame = QtWidgets.QFrame(inputFilesPrompt)
        self.profSalaryFrame.setGeometry(QtCore.QRect(140, 110, 511, 51))
        self.profSalaryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profSalaryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profSalaryFrame.setObjectName("profSalaryFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.profSalaryFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.profSalaryPath = QtWidgets.QLineEdit(self.profSalaryFrame)
        self.profSalaryPath.setObjectName("profSalaryPath")
        self.gridLayout_2.addWidget(self.profSalaryPath, 0, 1, 1, 1)
        self.profSalaryLabel = QtWidgets.QLabel(self.profSalaryFrame)
        self.profSalaryLabel.setObjectName("profSalaryLabel")
        self.gridLayout_2.addWidget(self.profSalaryLabel, 0, 3, 1, 1)
        self.profSalaryExplore = QtWidgets.QToolButton(self.profSalaryFrame)
        self.profSalaryExplore.setObjectName("profSalaryExplore")
        self.gridLayout_2.addWidget(self.profSalaryExplore, 0, 0, 1, 1)
        self.profListFrame = QtWidgets.QFrame(inputFilesPrompt)
        self.profListFrame.setGeometry(QtCore.QRect(140, 50, 511, 51))
        self.profListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profListFrame.setObjectName("profListFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.profListFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.profListPath = QtWidgets.QLineEdit(self.profListFrame)
        self.profListPath.setObjectName("profListPath")
        self.gridLayout.addWidget(self.profListPath, 0, 1, 1, 1)
        self.profListLabel = QtWidgets.QLabel(self.profListFrame)
        self.profListLabel.setObjectName("profListLabel")
        self.gridLayout.addWidget(self.profListLabel, 0, 3, 1, 1)
        self.profListExplore = QtWidgets.QToolButton(self.profListFrame)
        self.profListExplore.setObjectName("profListExplore")
        self.gridLayout.addWidget(self.profListExplore, 0, 0, 1, 1)
        self.confirmFilesBtn = QtWidgets.QPushButton(inputFilesPrompt)
        self.confirmFilesBtn.setGeometry(QtCore.QRect(30, 80, 91, 41))
        self.confirmFilesBtn.setObjectName("confirmFilesBtn")

        # buttons {{{
        self.confirmFilesBtn.clicked.connect(self.confirm_input)
        self.profSalaryExplore.clicked.connect(self.import_salary)
        self.profListExplore.clicked.connect(self.import_list)
        # }}}

        self.retranslateUi(inputFilesPrompt)
        QtCore.QMetaObject.connectSlotsByName(inputFilesPrompt)

    def retranslateUi(self, inputFilesPrompt):
        _translate = QtCore.QCoreApplication.translate
        inputFilesPrompt.setWindowTitle(_translate("inputFilesPrompt", "Form"))
        self.profSalaryLabel.setText(_translate("inputFilesPrompt", "فایل حقوق"))
        self.profSalaryExplore.setText(_translate("inputFilesPrompt", "..."))
        self.profListLabel.setText(_translate("inputFilesPrompt", "فایل اساتید"))
        self.profListExplore.setText(_translate("inputFilesPrompt", "..."))
        self.confirmFilesBtn.setText(_translate("inputFilesPrompt", "تایید فایل‌ها"))


    def import_list(self):
        q.tprint("This is import prof")

    def import_salary(self):
        q.tprint("This is import salary")

    def confirm_input(self):
        prof_path = self.profListPath.text()
        salary_path = self.profSalaryPath.text()
        q.tprint(f"confirm [Salary list: {salary_path}, Prof list: {prof_path}]")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inputFilesPrompt = QtWidgets.QWidget()
    ui = Ui_inputFilesPrompt()
    ui.setupUi(inputFilesPrompt)
    inputFilesPrompt.show()
    sys.exit(app.exec_())
