# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from output_dialog import Ui_Dialog_Output as q
from os import environ as getenv


class Ui_inputFilesPrompt(QtWidgets.QWidget):
    def setupUi(self, inputFilesPrompt):
        self.inputFilesPrompt = inputFilesPrompt
        inputFilesPrompt.setObjectName("inputFilesPrompt")
        inputFilesPrompt.resize(675, 332)
        self.profSalaryFrame = QtWidgets.QFrame(inputFilesPrompt)
        self.profSalaryFrame.setGeometry(QtCore.QRect(140, 110, 511, 51))
        self.profSalaryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profSalaryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profSalaryFrame.setObjectName("profSalaryFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.profSalaryFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.profSalaryPath = QtWidgets.QLineEdit(self.profSalaryFrame)
        self.profSalaryPath.setObjectName("profSalaryPath")
        self.gridLayout_2.addWidget(self.profSalaryPath, 0, 1, 1, 1)
        self.profSalaryExploreBtn = QtWidgets.QPushButton(self.profSalaryFrame)
        self.profSalaryExploreBtn.setObjectName("profSalaryExploreBtn")
        self.gridLayout_2.addWidget(self.profSalaryExploreBtn, 0, 0, 1, 1)
        self.profSalaryLabel = QtWidgets.QLabel(self.profSalaryFrame)
        self.profSalaryLabel.setObjectName("profSalaryLabel")
        self.gridLayout_2.addWidget(self.profSalaryLabel, 0, 3, 1, 1)
        self.profListFrame = QtWidgets.QFrame(inputFilesPrompt)
        self.profListFrame.setGeometry(QtCore.QRect(140, 50, 511, 51))
        self.profListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profListFrame.setObjectName("profListFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.profListFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.profListPath = QtWidgets.QLineEdit(self.profListFrame)
        self.profListPath.setObjectName("profListPath")
        self.gridLayout.addWidget(self.profListPath, 0, 1, 1, 1)
        self.profListLabel = QtWidgets.QLabel(self.profListFrame)
        self.profListLabel.setObjectName("profListLabel")
        self.gridLayout.addWidget(self.profListLabel, 0, 3, 1, 1)
        self.profListExploreBtn = QtWidgets.QPushButton(self.profListFrame)
        self.profListExploreBtn.setObjectName("profListExploreBtn")
        self.gridLayout.addWidget(self.profListExploreBtn, 0, 0, 1, 1)
        self.confirmFilesBtn = QtWidgets.QPushButton(inputFilesPrompt)
        self.confirmFilesBtn.setGeometry(QtCore.QRect(30, 140, 91, 41))
        self.confirmFilesBtn.setObjectName("confirmFilesBtn")

        self.profSalaryFrame2 = QtWidgets.QFrame(inputFilesPrompt)
        self.profSalaryFrame2.setGeometry(QtCore.QRect(140, 170, 511, 51))
        self.profSalaryFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profSalaryFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profSalaryFrame2.setObjectName("profSalaryFrame2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.profSalaryFrame2)

        self.gridLayout_3.setObjectName("gridLayout_3")
        self.profSalaryPath2 = QtWidgets.QLineEdit(self.profSalaryFrame2)
        self.profSalaryPath2.setObjectName("profSalaryPath2")
        self.gridLayout_3.addWidget(self.profSalaryPath2, 0, 1, 1, 1)
        self.profSalaryLabel2 = QtWidgets.QLabel(self.profSalaryFrame2)
        self.profSalaryLabel2.setObjectName("profSalaryLabel2")
        self.gridLayout_3.addWidget(self.profSalaryLabel2, 0, 3, 1, 1)
        self.profSalaryExploreBtn2 = QtWidgets.QPushButton(self.profSalaryFrame2)
        self.profSalaryExploreBtn2.setObjectName("profSalaryExploreBtn2")
        self.gridLayout_3.addWidget(self.profSalaryExploreBtn2, 0, 0, 1, 1)
        self.profFormulaFrame = QtWidgets.QFrame(inputFilesPrompt)
        self.profFormulaFrame.setGeometry(QtCore.QRect(140, 230, 511, 51))
        self.profFormulaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profFormulaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profFormulaFrame.setObjectName("profFormulaFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.profFormulaFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.profFormulaPath = QtWidgets.QLineEdit(self.profFormulaFrame)
        self.profFormulaPath.setObjectName("profFormulaPath")
        self.gridLayout_4.addWidget(self.profFormulaPath, 0, 1, 1, 1)
        self.profFormulaLabel = QtWidgets.QLabel(self.profFormulaFrame)
        self.profFormulaLabel.setObjectName("profFormulaLabel")
        self.gridLayout_4.addWidget(self.profFormulaLabel, 0, 3, 1, 1)
        self.profFormulaExploreBtn = QtWidgets.QPushButton(self.profFormulaFrame)
        self.profFormulaExploreBtn.setObjectName("profFormulaExploreBtn")
        self.gridLayout_4.addWidget(self.profFormulaExploreBtn, 0, 0, 1, 1)

        # buttons {{{
        self.confirmFilesBtn.clicked.connect(self.confirmFiles)
        self.profSalaryExploreBtn.clicked.connect(lambda: self.browseFiles('profSalaryPath'))
        self.profSalaryExploreBtn2.clicked.connect(lambda: self.browseFiles('profSalaryPath2'))
        self.profListExploreBtn.clicked.connect(lambda: self.browseFiles('profListPath'))
        self.profFormulaExploreBtn.clicked.connect(lambda: self.browseFiles('profFormulaPath'))
        # }}}

        self.retranslateUi(inputFilesPrompt)
        QtCore.QMetaObject.connectSlotsByName(inputFilesPrompt)

    def retranslateUi(self, inputFilesPrompt):
        _translate = QtCore.QCoreApplication.translate
        inputFilesPrompt.setWindowTitle(_translate("inputFilesPrompt", "Form"))
        self.profSalaryExploreBtn.setText(_translate("inputFilesPrompt", "جستجو"))
        self.profSalaryLabel.setText(_translate("inputFilesPrompt", "فایل حقوق"))
        self.profListLabel.setText(_translate("inputFilesPrompt", "فایل اساتید"))
        self.profListExploreBtn.setText(_translate("inputFilesPrompt", "جستجو"))
        self.confirmFilesBtn.setText(_translate("inputFilesPrompt", "تایید فایل‌ها"))
        self.profSalaryLabel2.setText(_translate("inputFilesPrompt", "فایل حقوق ۲"))
        self.profSalaryExploreBtn2.setText(_translate("inputFilesPrompt", "جستجو"))
        self.profFormulaLabel.setText(_translate("inputFilesPrompt", "فایل فرمول"))
        self.profFormulaExploreBtn.setText(_translate("inputFilesPrompt", "جستجو"))

    def browseFiles(self, lineEdit):
        filePath = QtWidgets.QFileDialog.getOpenFileName(self, 'Choose File', '', 'Excel Files (*.xlsx)')
        getattr(self, lineEdit).setText(filePath[0])

    def confirmFiles(self):
        _translate = QtCore.QCoreApplication.translate
        self.profSalaryLabel.setText(_translate("inputFilesPrompt", "فایل حقوق"))
        self.profListLabel.setText(_translate("inputFilesPrompt", "فایل اساتید"))
        self.profSalaryLabel2.setText(_translate("inputFilesPrompt", "فایل حقوق ۲"))

        # error handling
        # add error handling for the formula file
        err = 0
        if self.profListPath.text() == '':
            err += 1

        if self.profSalaryPath.text() == '':
            err += 2

        if self.profSalaryPath2.text() == '':
            err += 4

        # print(err, err % 7) # classic `perm` values for better error handling
        # maybe not a good way of doing it, idk and idc XD
        # wtf is this
        """
        it is what you are seeing XD
        some random idea which occured to me to get the errors based on sum of
        thoese three numbers which is exactly how file permissions in a unix
        system is working
        """
        # only thing that I am happy to implement while working on this shit so far
        # i see

        if err == 0:
            # save the path for later usage
            with open('inputFilesPath.txt', 'w') as file:
                file.write(f'{self.profListPath.text()}\n')
                file.write(f'{self.profSalaryPath.text()}\n')
                file.write(f'{self.profSalaryPath2.text()}\n')
                file.write(f'{self.profFormulaPath.text()}\n')
            self.inputFilesPrompt.close()
        # no need to specify which file is missing, just say choose all files imo
        else:
            q.tprint('لطفا تمام فایل ها را انتخاب کنید')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inputFilesPrompt = QtWidgets.QWidget()
    ui = Ui_inputFilesPrompt()
    ui.setupUi(inputFilesPrompt)
    inputFilesPrompt.show()
    sys.exit(app.exec_())
